# Generated by Django 3.2.7 on 2021-09-07 19:01

import administrator.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dp_name', models.CharField(max_length=255)),
                ('dp_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=255)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_email', models.CharField(max_length=255)),
                ('emp_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emp_department', models.IntegerField()),
                ('emp_designation', models.CharField(max_length=255)),
                ('emp_gender', models.CharField(max_length=50)),
                ('joined_date', models.DateField(max_length=50)),
                ('emp_password', models.CharField(max_length=50)),
                ('emp_img', models.ImageField(blank=True, null=True, upload_to=administrator.models.filepath)),
                ('emp_status', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to=administrator.models.filepath)),
                ('slider_status', models.CharField(max_length=50)),
            ],
        ),
    ]
